on:
  push:
    branches:
      - master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ secrets.server_ip }}
        username: ${{ secrets.fTP_USERNAM }}
        password: ${{ secrets.MAIN_FTP_PASSWORD }}
        server-dir: /public_html/account/